version: '2'
services:

  elasticsearch:
    image: elasticsearch:5.1
    expose:
      - 9200
    ports:
      - 9200:9200

  logstash:
    image: logstash:5.1
    volumes:
      - ./certs:/certs
      - ./conf:/conf
    expose:
      - 5044
    links:
      - elasticsearch
    command: logstash -f /conf/logstash.conf

  filebeat:
    build:
      context: .
      dockerfile: Dockerfile-filebeat
    volumes:
      - /var/log:/var/log
    links:
      - logstash

  kibana:
    image: kibana:5.1
    ports:
      - 5601:5601
    links:
      - elasticsearch